### ISSUE TITLE
Duplicated attachments in categories.

### ISSUE THREAD

**Issue by davidepedranz** [jmcameron/attachments#15]
First of all thanks for this great extension!

I have recently updated my website to Joomla 3.7.5. After the update, the attachments in the categories are duplicated: Joomla shows 2 boxes with the attachments. The download, management etc. is working perfectly, they are just shown twice in the categories. You can see the problem here: https://www.ciaminadanonesa.it/it/gara/edizione-2016.html

Is the problem already known?

**Comment by davidepedranz** [comment]
I am sorry, I have just took a look at the latest commits... it seems like you already fixed the issue!
I guess many people may be affected from this, so I would suggest to release an official update.

**Comment by jmcameron** [comment]
Yes.  I'm in the middle of various fixes and refactoring to only use jquery/boostrap (instead of mootools).  It may be a while before I can do a full release.  In any case, here is an unreleased version you can try:

    http://jmcameron.net/attachments/downloads/attachments-3.2.6-Beta4.zip

You should be able to install this over previous versions, but always BACKUP FIRST!

-Jonathan

**Comment by davidepedranz** [comment]
Thanks a lot Jonathan!

The funny point is that I did the Joomla update on a backup offline, but did not realised that the attachments were duplicated... So I broke the online website. I will pay more attention in the future!
